---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skupper-flow-collector
  labels:
    application: skupper-flow-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    application: skupper-flow-collector
  name: skupper-flow-collector
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    application: skupper-flow-collector
  name: skupper-flow-collector
subjects:
- kind: ServiceAccount
  name: skupper-flow-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skupper-flow-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-flow-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      application: skupper-flow-collector
  template:
    metadata:
      labels:
        application: skupper-flow-collector
        app.kubernetes.io/part-of: skupper
    spec:
      serviceAccountName: skupper-flow-collector
      # Please ensure that you can use SeccompProfile and do not use
      # if your project must work on old Kubernetes
      # versions < 1.19 or on vendors versions which
      # do NOT support this field by default
      securityContext:
        runAsNonRoot: true
        #seccompProfile:
          #type: RuntimeDefault
      containers:
      - name: skupper-flow-collector
        image: quay.io/skupper/flow-collector:1.9.4
        imagePullPolicy: Always
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        env:
        - name: SKUPPER_NAMESPACE
          valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /etc/messaging/
          name: skupper-local-client
      volumes:
      - name: skupper-local-client
        secret:
          secretName: skupper-local-client
---
apiVersion: v1
kind: Service
metadata:
  name: skupper-flow-collector
spec:
  ports:
  - port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    application: skupper-flow-collector
  type: ClusterIP
