FROM golang:1.13 AS builder

WORKDIR /go/src/app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN make build-tests

#TODO look for a smaller base image
FROM golang:1.13

WORKDIR /go/src/app
COPY --from=builder /go/src/app/tcp_echo_test .

CMD ["ls"]
