FROM golang:1.13 AS builder

WORKDIR /go/src/app

COPY go.mod .
COPY go.sum .
RUN go mod download && go get github.com/go-delve/delve/cmd/dlv

COPY . .
RUN make build-site-controller-debug


FROM registry.access.redhat.com/ubi8-minimal

EXPOSE 40001

WORKDIR /app
COPY --from=builder /go/src/app/site-controller .
COPY --from=builder /go/bin/dlv /
CMD ["/dlv", "--listen=:40001", "--headless=true", "--api-version=2", "exec", "/app/site-controller"]
