FROM golang:1.18 AS builder

WORKDIR /go/src/app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN make

FROM registry.access.redhat.com/ubi8-minimal

RUN microdnf install openssl && microdnf clean all

WORKDIR /app
COPY --from=builder /go/src/app/test/integration/bin ./

CMD ["ls"]
