{
 "title": "Skupper Control Plane",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(skupper_kubernetes_client_http_requests_total,container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$container Kube API Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "container"
  },
  {
   "title": "Container Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum without(kind) (skupper_workqueue_depth{container=\"$container\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Request Time",
   "type": "stat",
   "description": "Rate (per second) of time spent performing client requests",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(skupper_kubernetes_client_http_request_duration_seconds_sum{container=\"$container\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server HTTP Error Rate",
   "type": "timeseries",
   "description": "Rate of non-2xx http responses from the kube api server",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(skupper_kubernetes_client_http_requests_total{container=\"$container\", status_code!~\"2[0-9]{2}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "High Frequency HTTP Requests by Endpoint and Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by(exported_endpoint, method) (rate(skupper_kubernetes_client_http_request_duration_seconds_count{container=\"$container\"}[$__rate_interval])))",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Client Rate Limiting: P95 Duration",
   "type": "timeseries",
   "description": "Client side rate limiting duration",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(skupper_kubernetes_client_rate_limiter_duration_seconds_bucket{container=\"$container\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$container Responsiveness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "container",
   "collapsed": true,
   "panels": [
    {
     "title": "Responsiveness: P95 Work Queue Delay",
     "type": "timeseries",
     "description": "Estimated responsiveness: time from resource change to processing time",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(skupper_workqueue_delay_seconds_bucket{container=\"$container\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Work Duration by Kind",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(kind) (rate(skupper_workqueue_duration_seconds_sum{container=\"$container\"}[$__rate_interval])) / sum by(kind) (rate(skupper_workqueue_duration_seconds_count{container=\"controller\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queue Add Rate by Kind",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum by(kind) (rate(skupper_workqueue_adds_total{container=\"$container\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Worker Load Factor",
     "type": "timeseries",
     "description": "Theoretical worker load as a percentage. Queue add rate * Work Item Duration.",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(skupper_workqueue_duration_seconds_sum{container=\"$container\"}[$__rate_interval])) / sum(rate(skupper_workqueue_duration_seconds_count{container=\"$container\"}[$__rate_interval])) * sum(rate(skupper_workqueue_adds_total{container=\"$container\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Work Queue Depth",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(skupper_workqueue_depth{container=\"$container\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}