apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: attachedconnectors.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                siteNamespace:
                  type: string
                port:
                  type: integer
                selector:
                  type: string
                tlsCredentials:
                  type: string
                type:
                  type: string
                includeNotReady:
                  type: boolean
                settings:
                  type: object
                  additionalProperties:
                    type: string
              required:
              - port
              - selector
              - siteNamespace
            status:
              type: object
              properties:
                status:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        maxLength: 1024
                        minLength: 1
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        enum:
                        - "True"
                        - "False"
                        - Unknown
                        type: string
                      type:
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][- A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    required:
                    - lastTransitionTime
                    - message
                    - reason
                    - status
                    - type
                selectedPods:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      ip:
                        type: string
                matchingListenerCount:
                  type: integer
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Port
        type: integer
        description: The port to connect to.
        jsonPath: .spec.port
      - name: Selector
        type: string
        description: The selector that identifies the pods to connect to.
        jsonPath: .spec.selector
      - name: Site Namespace
        type: string
        description: The namespace in which the site this connector should be attached to is defined.
        jsonPath: .spec.siteNamespace
      - name: Status
        type: string
        description: The status of the connector.
        jsonPath: .status.status
  scope: Namespaced
  names:
    plural: attachedconnectors
    singular: attachedconnector
    kind: AttachedConnector
