apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sites.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                routerMode:
                  type: string
                serviceAccount:
                  type: string
                linkAccess:
                  type: string
                defaultIssuer:
                  type: string
                ha:
                  type: boolean
                settings:
                  type: object
                  additionalProperties:
                    type: string
            status:
              type: object
              properties:
                defaultIssuer:
                  type: string
                status:
                  type: string
                message:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        maxLength: 1024
                        minLength: 1
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        enum:
                        - "True"
                        - "False"
                        - Unknown
                        type: string
                      type:
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][- A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    required:
                    - lastTransitionTime
                    - message
                    - reason
                    - status
                    - type
                endpoints:
                  type: array
                  items:
                    type: object
                    properties:
                      host:
                        type: string
                      port:
                        type: string
                      name:
                        type: string
                      group:
                        type: string
                sitesInNetwork:
                  type: integer
                network:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                      platform:
                        type: string
                      version:
                        type: string
                      links:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            remoteSiteId:
                              type: string
                            remoteSiteName:
                              type: string
                            operational:
                              type: boolean
                      services:
                        type: array
                        items:
                          type: object
                          properties:
                            routingKey:
                              type: string
                            connectors:
                              type: array
                              items:
                                type: string
                            listeners:
                              type: array
                              items:
                                type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Status
        type: string
        description: The status of the site
        jsonPath: .status.status
      - name: Sites In Network
        type: integer
        description: The number of sites in the network
        jsonPath: .status.sitesInNetwork
      - name: Message
        type: string
        description: Any human readable message relevant to the site
        jsonPath: .status.message
  scope: Namespaced
  names:
    plural: sites
    singular: site
    kind: Site
