---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skupper-controller
  labels:
    application: skupper-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    application: skupper-controller
  name: skupper-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/exec
  - services
  - secrets
  - serviceaccounts
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
    - apps.openshift.io
  resources:
    - deploymentconfigs
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - skupper.io
  resources:
  - sites
  - sites/status
  - links
  - links/status
  - accesstokens
  - accesstokens/status
  - accessgrants
  - accessgrants/status
  - listeners
  - listeners/status
  - connectors
  - connectors/status
  - attachedconnectors
  - attachedconnectors/status
  - attachedconnectoranchors
  - attachedconnectoranchors/status
  - routeraccesses
  - routeraccesses/status
  - securedaccesses
  - securedaccesses/status
  - certificates
  - certificates/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    application: skupper-controller
  name: skupper-controller
subjects:
- kind: ServiceAccount
  name: skupper-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skupper-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      application: skupper-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: skupper
        application: skupper-controller
    spec:
      serviceAccountName: skupper-controller
      # Prevent kubernetes from injecting env vars for grant service
      # as these then collide with those that actually configure the
      # controller:
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: controller
        image: quay.io/skupper/controller:2.0.0-preview-1
        imagePullPolicy: Always
        command: ["/app/controller"]
        args: ["-enable-grants", "-grant-server-autoconfigure"]
        env:
        - name: SKUPPER_CONFIG_SYNC_IMAGE
          value: quay.io/skupper/config-sync:2.0.0-preview-1
        - name: WATCH_NAMESPACE
          valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: tls-credentials
          mountPath: /etc/controller
      volumes:
      - name: tls-credentials
        emptyDir: {}
