apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: linkaccesses.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                roles:
                  type: array
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                      port:
                        type: integer
                ca:
                  type: string
                accessType:
                  type: string
                tlsCredentials:
                  type: string
                bindHost:
                  type: string
                subjectAlternativeNames:
                  type: array
                  items:
                    type: string
                options:
                  type: object
                  additionalProperties:
                    type: string
              required:
              - roles
              - tlsCredentials
            status:
              type: object
              properties:
                active:
                  type: boolean
                status:
                  type: string
                urls:
                  type: array
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                      url:
                        type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Status
        type: string
        description: The status of the link access
        jsonPath: .status.status
  scope: Namespaced
  names:
    plural: linkaccesses
    singular: linkaccess
    kind: LinkAccess
