apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accessgrants.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                redemptionsAllowed:
                  type: integer
                expirationWindow:
                  type: string
                  format: duration
                code:
                  type: string
                issuer:
                  type: string
            status:
              type: object
              properties:
                url:
                  type: string
                code:
                  type: string
                ca:
                  type: string
                redeemed:
                  type: integer
                expiration:
                  type: string
                  format: date-time
                status:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Redemptions Allowed
        type: integer
        description: The number of claims the grant is valid for
        jsonPath: .spec.claims
      - name: Redemptions Made
        type: integer
        description: The number of times an access token originating from this grant has been redeemed
        jsonPath: .status.redeemed
      - name: Expiration
        type: string
        description: When the grant will expire
        jsonPath: .status.expiration
      - name: Status
        type: string
        description: The status of the grant
        jsonPath: .status.status
  scope: Namespaced
  names:
    plural: accessgrants
    singular: accessgrant
    kind: AccessGrant
