apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grants.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                claims:
                  type: integer
                validFor:
                  type: string
                  format: duration
                secret:
                  type: string
            status:
              type: object
              properties:
                url:
                  type: string
                secret:
                  type: string
                ca:
                  type: string
                claimed:
                  type: integer
                expiration:
                  type: string
                  format: date-time
                status:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Claims Allowed
        type: integer
        description: The number of claims the grant is valid for
        jsonPath: .spec.claims
      - name: Claims Made
        type: integer
        description: The number of times the grant has been claimed
        jsonPath: .status.claimed
      - name: Expiration
        type: string
        description: When the grant will expire
        jsonPath: .status.expiration
      - name: Status
        type: string
        description: The status of the grant
        jsonPath: .status.status
  scope: Namespaced
  names:
    plural: grants
    singular: grant
    kind: Grant
