apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accesstokens.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
                code:
                  type: string
                ca:
                  type: string
              required:
              - url
              - code
              - ca
            status:
              type: object
              properties:
                redeemed:
                  type: boolean
                status:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: URL
        type: string
        description: The URL the access token is redeemed at
        jsonPath: .spec.url
      - name: Redeemed
        type: boolean
        description: Whether the access token has already been redeemed
        jsonPath: .status.redeemed
      - name: Status
        type: string
        description: The status of the access token
        jsonPath: .status.status
  scope: Namespaced
  names:
    plural: accesstokens
    singular: accesstoken
    kind: AccessToken
