apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: connectors.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                routingKey:
                  type: string
                port:
                  type: integer
                selector:
                  type: string
                host:
                  type: string
                tlsCredentials:
                  type: string
                type:
                  type: string
                includeNotReady:
                  type: boolean
              required:
              - routingKey
              - port
              oneOf:
                - properties:
                  required:
                  - selector
                - properties:
                  required:
                  - host
            status:
              type: object
              properties:
                status:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        maxLength: 1024
                        minLength: 1
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        enum:
                        - "True"
                        - "False"
                        - Unknown
                        type: string
                      type:
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][- A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    required:
                    - lastTransitionTime
                    - message
                    - reason
                    - status
                    - type
                selectedPods:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      ip:
                        type: string
                matchingListenerCount:
                  type: integer
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Routing Key
        type: string
        description: The key that ties connectors and listeners together
        jsonPath: .spec.routingKey
      - name: Port
        type: integer
        description: The port to connect to
        jsonPath: .spec.port
      - name: Host
        type: string
        description: The host to connect to
        jsonPath: .spec.host
      - name: Selector
        type: string
        description: The selector that identifies the pods to connect to
        jsonPath: .spec.selector
      - name: Status
        type: string
        description: The status of the connector
        jsonPath: .status.status
      - name: Matching Listener Count
        type: integer
        description: The number of listeners in the network with a matching routing key.
        jsonPath: .status.matchingListenerCount
  scope: Namespaced
  names:
    plural: connectors
    singular: connector
    kind: Connector
