name: "Install latest podman"
description: "Installs latest development version of podman"
author: "fgiorgetti@gmail.com"
runs:
  using: "composite"
  steps:
    - id: install-latest-podman
      shell: bash
      run: |
        sudo mkdir -p /etc/apt/keyrings
        
        # Debian Testing/Bookworm
        curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/Release.key \
          | gpg --dearmor \
          | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
            https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/ /" \
          | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
        
        # Debian Unstable/Sid
        curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/Release.key \
          | gpg --dearmor \
          | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
            https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/ /" \
          | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
        
        # Install Podman
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get -y install podman

        # Displaying podman version
        podman version
    - id: run-podman-socket
      shell: bash
      run: |
        # Starting systemd user service
        systemctl --user start podman.socket
        systemctl --user status podman.socket
