apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-controller
spec:
  selector:
    matchLabels:
      application: skupper-controller
  template:
    spec:
      containers:
        - name: controller
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace