apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Name }}
spec:
  gatewayClassName: {{ .Class }}
  listeners:
  - name: tls
    protocol: TLS
    port: {{ .Port }}
    tls:
      mode: Passthrough
    allowedRoutes:
      namespaces:
        from: All
