---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: network-observer-prometheus
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-observer-prometheus
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-observer-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: network-observer-prometheus
subjects:
- kind: ServiceAccount
  name: network-observer-prometheus
---
apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
    rule_files:
    scrape_configs:
      - job_name: network-observer-service
        kubernetes_sd_configs:
        - role: service
          kubeconfig_file: ""
          follow_redirects: true
          enable_http2: true
          namespaces:
            own_namespace: true
        scheme: https
        tls_config:
          insecure_skip_verify: true
        follow_redirects: true
        enable_http2: true
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
          regex: network-observer
          action: keep
        - source_labels: [__meta_kubernetes_service_port_name]
          regex: https
          action: keep
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
          replacement: $1
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service

  web-config.yml: |
    # TLS configuration.
    #
    #tls_server_config:
    #  cert_file: /etc/tls/certs/tls.crt
    #  key_file: /etc/tls/certs/tls.key
kind: ConfigMap
metadata:
  name: prometheus-server-config
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: network-observer-prometheus
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/component: metrics
  name: network-observer-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: network-observer-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: network-observer-prometheus
        app.kubernetes.io/part-of: skupper-network-observer
        app.kubernetes.io/component: metrics
    spec:
      containers:
      - args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        - --web.config.file=/etc/prometheus/web-config.yml
        image: quay.io/prometheus/prometheus:v2.42.0
        imagePullPolicy: Always
        name: prometheus-server
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-config
        - mountPath: /prometheus
          name: prometheus-storage-volume
      serviceAccount: network-observer-prometheus
      serviceAccountName: network-observer-prometheus
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-server-config
        name: prometheus-config
      - emptyDir: {}
        name: prometheus-storage-volume
---
apiVersion: v1
kind: Service
metadata:
  name: network-observer-prometheus
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/name: network-observer-prometheus
spec:
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: network-observer-prometheus
    app.kubernetes.io/component: metrics
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: network-observer-issuer
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: network-observer-cert
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
spec:
  commonName: network-observer
  secretName: network-observer-certs
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: network-observer-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: skupper.io/v2alpha1
kind: Certificate
metadata:
  name: skupper-management-client
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
spec:
  ca: skupper-local-ca
  hosts:
  - skupper-router-local
  client: true
  subject: skupper-router-local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/component: server
  name: network-observer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: skupper-network-observer
      app.kubernetes.io/name: network-observer
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: skupper-network-observer
        app.kubernetes.io/name: network-observer
        app.kubernetes.io/component: server
    spec:
      containers:
      - image: quay.io/skupper/network-observer:v2-dev
        imagePullPolicy: Always
        name: network-observer
        args:
          - -listen=:8443
          - -cors-allow-all
          - -tls-cert=/etc/console/tls.crt
          - -tls-key=/etc/console/tls.key
          - -router-endpoint=amqps://skupper-router-local
          - -router-tls-ca=/etc/messaging/ca.crt
          - -router-tls-cert=/etc/messaging/tls.crt
          - -router-tls-key=/etc/messaging/tls.key
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /etc/console/
          name: network-observer-certs
        - mountPath: /etc/messaging/
          name: skupper-management-client
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
      volumes:
      - name: network-observer-certs
        secret:
          defaultMode: 420
          secretName: network-observer-certs
      - name: skupper-management-client
        secret:
          defaultMode: 420
          secretName: skupper-management-client
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/name: network-observer
  name: network-observer
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/component: server
  type: LoadBalancer

