apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accesstokens.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: |-
            A short-lived credential used to create a link between sites.
            An access token contains the URL and secret code of a corresponding access grant.
            **Note:** Access tokens are typically issued and redeemed using the Skupper CLI.
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  description: |-
                    The URL of the grant service at the remote site.
                  type: string
                code:
                  description: |-
                    The secret code used to authenticate the token when submitted for redemption.
                  type: string
                ca:
                  description: |-
                    The trusted server certificate of the grant service at the remote site.
                  type: string
                linkCost:
                  description: |-
                    The link cost to use when creating the link.
                  type: integer
                settings:
                  description: |-
                    Advanced. A map containing additional settings. Each map
                    entry has a string name and a string value.

                    **Note:** In  general, we recommend not changing settings
                    from their default values.
                  type: object
                  additionalProperties:
                    type: string
              required:
              - url
              - code
              - ca
            status:
              type: object
              properties:
                redeemed:
                  description: |-
                    True if the token has been redeemed. Once a token is redeemed, it cannot be used again.
                  type: boolean
                status:
                  description: |-
                    The current state of the resource.
                    - `Pending`: The resource is being processed.
                    - `Error`: There was an error processing the resource. See `message` for more information.
                    - `Ready`: The resource is ready to use.
                  type: string
                message:
                  description: |-
                    A human-readable status message. Error messages are reported here.
                  type: string
                conditions:
                  type: array
                  description: |-
                    A set of named conditions describing the current state of the resource.

                    - `Redeemed`: The token has been exchanged for a link.
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        maxLength: 1024
                        minLength: 1
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        enum:
                        - "True"
                        - "False"
                        - Unknown
                        type: string
                      type:
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    required:
                    - lastTransitionTime
                    - message
                    - reason
                    - status
                    - type
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: URL
        type: string
        description: The URL the access token is redeemed at
        jsonPath: .spec.url
      - name: Redeemed
        type: boolean
        description: Whether the access token has already been redeemed
        jsonPath: .status.redeemed
      - name: Status
        type: string
        description: The status of the access token
        jsonPath: .status.status
      - name: Message
        type: string
        description: Any human readable message relevant to the token
        jsonPath: .status.message
  scope: Namespaced
  names:
    plural: accesstokens
    singular: accesstoken
    kind: AccessToken
    shortNames:
    - token
    - to
