apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: securedaccesses.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: "An internal resource used to create secure access to pods"
          type: object
          properties:
            spec:
              type: object
              properties:
                ports:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      port:
                        type: integer
                      targetPort:
                        type: integer
                      protocol:
                        type: string
                    required:
                    - name
                    - port
                selector:
                  type: object
                  additionalProperties:
                    type: string
                issuer:
                  type: string
                certificate:
                  type: string
                accessType:
                  type: string
                settings:
                  type: object
                  additionalProperties:
                    type: string
              required:
              - selector
              - ports
            status:
              type: object
              properties:
                endpoints:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      host:
                        type: string
                      port:
                        type: string
                      group:
                        type: string
                ca:
                  type: string
                status:
                  type: string
                message:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        maxLength: 1024
                        minLength: 1
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        enum:
                        - "True"
                        - "False"
                        - Unknown
                        type: string
                      type:
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    required:
                    - lastTransitionTime
                    - message
                    - reason
                    - status
                    - type
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Status
        type: string
        description: The status of the secured access
        jsonPath: .status.status
      - name: Message
        type: string
        description: Any relevant human readable message
        jsonPath: .status.message
  scope: Namespaced
  names:
    plural: securedaccesses
    singular: securedaccess
    kind: SecuredAccess
