apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accesstokens.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: "A short-lived credential used to create a link"
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
                code:
                  type: string
                ca:
                  type: string
                linkCost:
                  type: integer
                settings:
                  type: object
                  additionalProperties:
                    type: string
              required:
              - url
              - code
              - ca
            status:
              type: object
              properties:
                redeemed:
                  type: boolean
                status:
                  type: string
                message:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        maxLength: 1024
                        minLength: 1
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        enum:
                        - "True"
                        - "False"
                        - Unknown
                        type: string
                      type:
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    required:
                    - lastTransitionTime
                    - message
                    - reason
                    - status
                    - type
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: URL
        type: string
        description: The URL the access token is redeemed at
        jsonPath: .spec.url
      - name: Redeemed
        type: boolean
        description: Whether the access token has already been redeemed
        jsonPath: .status.redeemed
      - name: Status
        type: string
        description: The status of the access token
        jsonPath: .status.status
      - name: Message
        type: string
        description: Any human readable message relevant to the token
        jsonPath: .status.message
  scope: Namespaced
  names:
    plural: accesstokens
    singular: accesstoken
    kind: AccessToken
    shortNames:
    - token
    - to
