// Code generated by network-console-controller codegen. DO NOT EDIT
package api

// Implements ResponseSetter and CollectionResponseSetter for the generated
// response objects

// SetCount
func (r *AddressListResponse) SetCount(v int64) {
	r.Count = v
}

// SetResults
func (r *AddressListResponse) SetResults(v []AddressRecord) {
	r.Results = v
}

// SetTimeRangeCount
func (r *AddressListResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}

// SetResults
func (r *AddressResponse) SetResults(v AddressRecord) {
	r.Results = v
}

// SetCount
func (r *ConnectorListResponse) SetCount(v int64) {
	r.Count = v
}

// SetResults
func (r *ConnectorListResponse) SetResults(v []ConnectorRecord) {
	r.Results = v
}

// SetTimeRangeCount
func (r *ConnectorListResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}

// SetResults
func (r *ConnectorResponse) SetResults(v ConnectorRecord) {
	r.Results = v
}

// SetCount
func (r *FlowAggregateListResponse) SetCount(v int64) {
	r.Count = v
}

// SetResults
func (r *FlowAggregateListResponse) SetResults(v []FlowAggregateRecord) {
	r.Results = v
}

// SetTimeRangeCount
func (r *FlowAggregateListResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}

// SetResults
func (r *FlowAggregateResponse) SetResults(v FlowAggregateRecord) {
	r.Results = v
}

// SetCount
func (r *LinkListResponse) SetCount(v int64) {
	r.Count = v
}

// SetResults
func (r *LinkListResponse) SetResults(v []LinkRecord) {
	r.Results = v
}

// SetTimeRangeCount
func (r *LinkListResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}

// SetResults
func (r *LinkResponse) SetResults(v LinkRecord) {
	r.Results = v
}

// SetCount
func (r *ListenerListResponse) SetCount(v int64) {
	r.Count = v
}

// SetResults
func (r *ListenerListResponse) SetResults(v []ListenerRecord) {
	r.Results = v
}

// SetTimeRangeCount
func (r *ListenerListResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}

// SetResults
func (r *ListenerResponse) SetResults(v ListenerRecord) {
	r.Results = v
}

// SetCount
func (r *ProcessGroupListResponse) SetCount(v int64) {
	r.Count = v
}

// SetResults
func (r *ProcessGroupListResponse) SetResults(v []ProcessGroupRecord) {
	r.Results = v
}

// SetTimeRangeCount
func (r *ProcessGroupListResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}

// SetResults
func (r *ProcessGroupResponse) SetResults(v ProcessGroupRecord) {
	r.Results = v
}

// SetCount
func (r *ProcessListResponse) SetCount(v int64) {
	r.Count = v
}

// SetResults
func (r *ProcessListResponse) SetResults(v []ProcessRecord) {
	r.Results = v
}

// SetTimeRangeCount
func (r *ProcessListResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}

// SetResults
func (r *ProcessResponse) SetResults(v ProcessRecord) {
	r.Results = v
}

// SetCount
func (r *RouterAccessListResponse) SetCount(v int64) {
	r.Count = v
}

// SetResults
func (r *RouterAccessListResponse) SetResults(v []RouterAccessRecord) {
	r.Results = v
}

// SetTimeRangeCount
func (r *RouterAccessListResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}

// SetResults
func (r *RouterAccessResponse) SetResults(v RouterAccessRecord) {
	r.Results = v
}

// SetCount
func (r *RouterLinkListResponse) SetCount(v int64) {
	r.Count = v
}

// SetResults
func (r *RouterLinkListResponse) SetResults(v []RouterLinkRecord) {
	r.Results = v
}

// SetTimeRangeCount
func (r *RouterLinkListResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}

// SetResults
func (r *RouterLinkResponse) SetResults(v RouterLinkRecord) {
	r.Results = v
}

// SetCount
func (r *RouterListResponse) SetCount(v int64) {
	r.Count = v
}

// SetResults
func (r *RouterListResponse) SetResults(v []RouterRecord) {
	r.Results = v
}

// SetTimeRangeCount
func (r *RouterListResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}

// SetResults
func (r *RouterResponse) SetResults(v RouterRecord) {
	r.Results = v
}

// SetCount
func (r *SiteListResponse) SetCount(v int64) {
	r.Count = v
}

// SetResults
func (r *SiteListResponse) SetResults(v []SiteRecord) {
	r.Results = v
}

// SetTimeRangeCount
func (r *SiteListResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}

// SetResults
func (r *SiteResponse) SetResults(v SiteRecord) {
	r.Results = v
}

// SetCount
func (r *CollectionResponse) SetCount(v int64) {
	r.Count = v
}

// SetTimeRangeCount
func (r *CollectionResponse) SetTimeRangeCount(v int64) {
	r.TimeRangeCount = v
}
