apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: routeraccesses.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                roles:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      port:
                        type: integer
                generateTlsCredentials:
                  type: boolean
                issuer:
                  type: string
                accessType:
                  type: string
                tlsCredentials:
                  type: string
                bindHost:
                  type: string
                subjectAlternativeNames:
                  type: array
                  items:
                    type: string
                settings:
                  type: object
                  additionalProperties:
                    type: string
              required:
              - roles
              - tlsCredentials
            status:
              type: object
              properties:
                status:
                  type: string
                message:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        maxLength: 1024
                        minLength: 1
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        enum:
                        - "True"
                        - "False"
                        - Unknown
                        type: string
                      type:
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][- A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    required:
                    - lastTransitionTime
                    - message
                    - reason
                    - status
                    - type
                endpoints:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      host:
                        type: string
                      port:
                        type: string
                      group:
                        type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Status
        type: string
        description: The status of the router access
        jsonPath: .status.status
      - name: Message
        type: string
        description: Any relevant human readable message
        jsonPath: .status.message
  scope: Namespaced
  names:
    plural: routeraccesses
    singular: routeraccess
    kind: RouterAccess
